### PR TITLE
Added twig loader extension for references

### PR DESCRIPTION
**Pull request by stephenwf**
Mentioned as a more scalable way to include references to other twig templates.

### CODE REVIEW

**Review by davidcmoulton — COMMENTED** [review]
Spinning this up, I see build warnings similar to this one for each twig template:
```
WARNING in ./src/patterns/molecules/heading/heading.twig
Module build failed (from ./.storybook/loaders/twig-loader-plus.js):
TypeError: Cannot read property 'split' of undefined
    at stringifyRequest (/app/node_modules/loader-utils/lib/stringifyRequest.js:16:28)
    at Object.twigLoaderPlus (/app/.storybook/loaders/twig-loader-plus.js:15:74)
 @ ./src/patterns sync \.twig$ ./molecules/heading/heading.twig
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by stephenwf** [comment]
@davidcmoulton ah right, late addition of `stringifyRequest` broke it, fix that now 👍

**Comment by thewilkybarkid** [comment]
Was hoping this would fix the Twig reload problem, but doesn't...

**Comment by stephenwf** [comment]
@thewilkybarkid What the details of the Twig loading problem?

**Comment by thewilkybarkid** [comment]
@stephenwf Make a change to a template, it doesn't update and there's an error in the console.

**Pull request closed without merging**
